packages:
  - packages/*
  - examples/*
  - playground
  - docs

catalog:
  '@adonisjs/core': ^7.3.3

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@taskforcesh/bullmq-pro'
  - '@adonisjs/*'
